# Generated by Django 6.1.1 on 2026-09-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_customuser_groups_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Multiple choice'), (2, 'Boolean'), (3, 'Dropdown'), (4, 'Numerical')], default=1),
        ),
    ]
