# Generated by Django 6.1.1 on 2026-09-25 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher')], default=1),
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Multiple choice'), (2, 'Boolean'), (3, 'Dropdown'), (4, 'Numerical')], default=1)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('incorrect', models.JSONField(blank=True, default=list)),
                ('submitted', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='quiz.question')),
            ],
        ),
    ]
